FROM nvcr.io/nvidia/pytorch:23.05-py3

RUN apt update -y && \
    apt install -y zip htop screen libgl1-mesa-glx && \
    mkdir /workspace

WORKDIR /workspace

COPY ./requirements.txt /workspace/requirements.txt

RUN pip install -r /workspace/requirements.txt

ENTRYPOINT ["nvidia-smi"]