import math
CAMERA_MODEL = 1

# INTEL REALSENSE
IRSCAM_FOV = 130 # DEGREES
IRSCAM_IMAGE_PHEIGHT = 1920 # PIXELS
IRSCAM_IMAGE_PWIDTH = 1920 # PIXELS

IRSCAM_ASPECT_RATIO = IRSCAM_IMAGE_PWIDTH/IRSCAM_IMAGE_PHEIGHT
IRSCAM_Z_C_SCALED = (IRSCAM_IMAGE_PHEIGHT/2)/math.tan( math.radians(IRSCAM_FOV) / 2 )

# HWIL SIMULATED CAMERA (HSCAM)
HSCAM_FOV = 130 # DEGREES
HSCAM_IMAGE_PHEIGHT = 1920 # PIXELS
HSCAM_IMAGE_PWIDTH = 1920 # PIXELS

HSCAM_ASPECT_RATIO = HSCAM_IMAGE_PWIDTH/HSCAM_IMAGE_PHEIGHT
HSCAM_Z_C_SCALED = (HSCAM_IMAGE_PHEIGHT/2)/math.tan( math.radians(HSCAM_FOV) / 2 )
