version: "3"

services:
  
  misc:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_misc:1.0
    shm_size: '64g'
    container_name: utxyolo_misc
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  train-data:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_train_data:1.0
    shm_size: '64g'
    container_name: utxyolo_train_data
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: bash -c "make train"

  stack-test:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_stack_test:1.0
    shm_size: '64g'
    container_name: utxyolo_stack_test
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: bash -c "make run_sitest_identification"