version: "3"

services:
  
  misc:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_misc:1.0
    shm_size: '64g'
    container_name: utxyolo_misc
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  train-data:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_train_data:1.0
    shm_size: '64g'
    container_name: utxyolo_train_data
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: bash -c "make train"

  # detect-item:
  #   build:
  #     context: ./
  #     shm_size: '64g'
  #     dockerfile: ./Dockerfile-utcdusxyolo
  #   image: utexascdus/utcdusxyolo_detect_item:1.0
  #   shm_size: '64g'
  #   container_name: utxyolo_detect_item
  #   volumes: 
  #     - ../src:/workspace_utcdusxyolo/
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   command: bash -c "make test_composite_on_item"

  detect-test:
    build:
      context: ./
      shm_size: '64g'
      dockerfile: ./Dockerfile-utcdusxyolo
    image: utexascdus/utcdusxyolo_detect_item:1.0
    shm_size: '64g'
    container_name: utxyolo_detect_item
    volumes: 
      - ../src:/workspace_utcdusxyolo/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: bash -c "make test_misc_detect"